// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Enable disable users
---
*/
package cmds

import (
	"context"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/utils"
)

func AuthEnableDisabledPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "azure-users", "authentication", "30-enable-users-for-domain-oneliner.ps1", "", "-domain", args[0])
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
