// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Reset MFA
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/schemas"
	"github.com/365admin/azure-users/utils"
)

func AzureadResetMfaPost(ctx context.Context, body []byte, args []string) (*schemas.UsersMfaresetDone, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("azure-users"), "users.mfareset.do.json"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	result, pwsherr := execution.ExecutePowerShell("john", "*", "azure-users", "30-azuread", "30-reset-mfa.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("azure-users"), "users.mfareset.done.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.UsersMfaresetDone{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
