// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Web deploy to production
---
*/
package cmds

import (
	"context"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/utils"
)

func DeploywebWebdeployproductionPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "azure-users", "60-deploy-web", "20-web.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
