// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Refresh PEP.PL users
---
*/
package cmds

import (
	"context"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/utils"
)

func MagicPepplPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "azure-users", "00-magic", "10-pep.pl-sync.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
