// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Enable disable users
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/azure-users/execution"
)

func AuthEnableDisabledPost() usecase.Interactor {
	type Request struct {
		Domain string `query:"domain" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "azure-users", "authentication", "30-enable-users-for-domain-oneliner.ps1", "", "-domain", input.Domain)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Enable disable users")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Authentication")
	return u
}
