// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Find users matching a given domain
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/schemas"
	"github.com/365admin/azure-users/utils"
)

func AzureadFindUsersPost() usecase.Interactor {
	type Request struct {
		Domain string `query:"domain" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.UsersFound) error {

		_, err := execution.ExecutePowerShell("john", "*", "azure-users", "30-azuread", "05-find-emails.ps1", "", "-domain", input.Domain)
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("azure-users"), "users.found.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.UsersFound{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Find users matching a given domain")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Azure AD")
	return u
}
