// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Reset MFA
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/schemas"
	"github.com/365admin/azure-users/utils"
)

func AzureadResetMfaPost() usecase.Interactor {
	type Request struct {
		Body schemas.UsersMfaresetDo `json:"body" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.UsersMfaresetDone) error {
		body, inputErr := json.Marshal(input.Body)
		if inputErr != nil {
			return inputErr
		}

		inputErr = os.WriteFile(path.Join(utils.WorkDir("azure-users"), "users.mfareset.do.json"), body, 0644)
		if inputErr != nil {
			return inputErr
		}

		_, err := execution.ExecutePowerShell("john", "*", "azure-users", "30-azuread", "30-reset-mfa.ps1", "")
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("azure-users"), "users.mfareset.done.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.UsersMfaresetDone{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Reset MFA")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Azure AD")
	return u
}
