// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Get Users to MFA reset
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/azure-users/execution"
	"github.com/365admin/azure-users/schemas"
	"github.com/365admin/azure-users/utils"
)

func TasksGetUsersToMfaresetPost() usecase.Interactor {
	type Request struct {
		Domain string `query:"domain" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.UsersMfaresetDo) error {

		_, err := execution.ExecutePowerShell("john", "*", "azure-users", "20-tasks", "10 get-users-to-mfareset.do.ps1", "", "-domain", input.Domain)
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("azure-users"), "users.mfareset.do.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.UsersMfaresetDo{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Get Users to MFA reset")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Tasks")
	return u
}
